version: '3'
services:
  web:
    build: .
    env_file:
      - ./environments/docker.env
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/mongodb/db:/data/db
